# Generated by Django 4.1.5 on 2023-01-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_rename_apointment_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
